### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by alienzj** [zwkno1/httpdump#1]
```-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
-- Pcap include dirs set to /usr/include
-- Pcap library set to  /lib/libpcap.so
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   system
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Protobuf_LIBRARY
    linked by target "test_pb" in directory /home/alienzj/projects/httpdump/plugin/test_pb
    linked by target "RTB" in directory /home/alienzj/projects/httpdump/plugin/rtb

-- Configuring incomplete, errors occurred!
See also "/home/alienzj/projects/httpdump/build/CMakeFiles/CMakeOutput.log".
See also "/home/alienzj/projects/httpdump/build/CMakeFiles/CMakeError.log".```

**Comment by alienzj** [comment]
fixed

**Comment by jiangnanfei** [comment]
how？

**Comment by zwkno1** [comment]
> how？
install protobuf

**Comment by jiangnanfei** [comment]
> how？
> install protobuf

emmmm，I have installed  that，but it still didn‘t work

**Comment by zwkno1** [comment]
> > how？
> > install protobuf
> 
> emmmm，I have installed that，but it still didn‘t work

pull and retry again

**Comment by jiangnanfei** [comment]
> how？
> install protobuf
> 
> emmmm，I have installed that，but it still didn‘t work
> 
> pull and retry again

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/x/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib64/librt.so;/home/x/cuda-linux64-nvjpeg/lib64/libnvjpeg.so;/home/x/cuda/lib64/libnppicom_static.a;/home/x/cuda/lib64/libnppicc_static.a;/home/x/cuda/lib64/libnppig_static.a;/home/x/cuda/lib64/libnppc_static.a;/home/x/cuda/lib64/libculibos.a;opencv_core;opencv_imgproc;opencv_imgcodecs;/usr/lib64/libjpeg.so;avformat;avformat;avcodec;avfilter;avutil;Protobuf_LIBRARY
    linked by target "dali_test.bin" in directory /home/x/dali/dali
Protobuf_LIBRARY
    linked by target "dali" in directory /home/x/dali/dali
    linked by target "dali_benchmark.bin" in directory /home/x/dali/dali

-- Configuring incomplete, errors occurred!
See also "/home/x/dali/build/CMakeFiles/CMakeOutput.log".
See also "/home/x/dali/build/CMakeFiles/CMakeError.log".

error like this ......,Sincerely thank you !!!! ,but do you sure for that retrying again will be useful?

**Comment by zwkno1** [comment]
> > how？
> > install protobuf
> > emmmm，I have installed that，but it still didn‘t work
> > pull and retry again
> 
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> /home/x/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib64/librt.so;/home/x/cuda-linux64-nvjpeg/lib64/libnvjpeg.so;/home/x/cuda/lib64/libnppicom_static.a;/home/x/cuda/lib64/libnppicc_static.a;/home/x/cuda/lib64/libnppig_static.a;/home/x/cuda/lib64/libnppc_static.a;/home/x/cuda/lib64/libculibos.a;opencv_core;opencv_imgproc;opencv_imgcodecs;/usr/lib64/libjpeg.so;avformat;avformat;avcodec;avfilter;avutil;Protobuf_LIBRARY
> linked by target "dali_test.bin" in directory /home/x/dali/dali
> Protobuf_LIBRARY
> linked by target "dali" in directory /home/x/dali/dali
> linked by target "dali_benchmark.bin" in directory /home/x/dali/dali
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/x/dali/build/CMakeFiles/CMakeOutput.log".
> See also "/home/x/dali/build/CMakeFiles/CMakeError.log".
> 
> error like this ......,Sincerely thank you !!!! ,but do you sure for that retrying again will be useful?

1. clean build directory
2. git pull
3. build

**Comment by jiangnanfei** [comment]
> how？
> install protobuf
> emmmm，I have installed that，but it still didn‘t work
> pull and retry again
> 
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> /home/x/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib64/librt.so;/home/x/cuda-linux64-nvjpeg/lib64/libnvjpeg.so;/home/x/cuda/lib64/libnppicom_static.a;/home/x/cuda/lib64/libnppicc_static.a;/home/x/cuda/lib64/libnppig_static.a;/home/x/cuda/lib64/libnppc_static.a;/home/x/cuda/lib64/libculibos.a;opencv_core;opencv_imgproc;opencv_imgcodecs;/usr/lib64/libjpeg.so;avformat;avformat;avcodec;avfilter;avutil;Protobuf_LIBRARY
> linked by target "dali_test.bin" in directory /home/x/dali/dali
> Protobuf_LIBRARY
> linked by target "dali" in directory /home/x/dali/dali
> linked by target "dali_benchmark.bin" in directory /home/x/dali/dali
> -- Configuring incomplete, errors occurred!
> See also "/home/x/dali/build/CMakeFiles/CMakeOutput.log".
> See also "/home/x/dali/build/CMakeFiles/CMakeError.log".
> error like this ......,Sincerely thank you !!!! ,but do you sure for that retrying again will be useful?
> 
> 
> clean build directory
> git pull
> build

 I 
wil try right now

**Comment by zwkno1** [comment]
> > how？
> > install protobuf
> > emmmm，I have installed that，but it still didn‘t work
> > pull and retry again
> > CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> > Please set them or make sure they are set and tested correctly in the CMake files:
> > /home/x/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib64/librt.so;/home/x/cuda-linux64-nvjpeg/lib64/libnvjpeg.so;/home/x/cuda/lib64/libnppicom_static.a;/home/x/cuda/lib64/libnppicc_static.a;/home/x/cuda/lib64/libnppig_static.a;/home/x/cuda/lib64/libnppc_static.a;/home/x/cuda/lib64/libculibos.a;opencv_core;opencv_imgproc;opencv_imgcodecs;/usr/lib64/libjpeg.so;avformat;avformat;avcodec;avfilter;avutil;Protobuf_LIBRARY
> > linked by target "dali_test.bin" in directory /home/x/dali/dali
> > Protobuf_LIBRARY
> > linked by target "dali" in directory /home/x/dali/dali
> > linked by target "dali_benchmark.bin" in directory /home/x/dali/dali
> > -- Configuring incomplete, errors occurred!
> > See also "/home/x/dali/build/CMakeFiles/CMakeOutput.log".
> > See also "/home/x/dali/build/CMakeFiles/CMakeError.log".
> > error like this ......,Sincerely thank you !!!! ,but do you sure for that retrying again will be useful?
> > clean build directory
> > git pull
> > build
> 
> I
> wil try right now

you will like it. you can star this repo.

**Comment by jiangnanfei** [comment]
> how？
> install protobuf
> emmmm，I have installed that，but it still didn‘t work
> pull and retry again
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> /home/x/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib64/librt.so;/home/x/cuda-linux64-nvjpeg/lib64/libnvjpeg.so;/home/x/cuda/lib64/libnppicom_static.a;/home/x/cuda/lib64/libnppicc_static.a;/home/x/cuda/lib64/libnppig_static.a;/home/x/cuda/lib64/libnppc_static.a;/home/x/cuda/lib64/libculibos.a;opencv_core;opencv_imgproc;opencv_imgcodecs;/usr/lib64/libjpeg.so;avformat;avformat;avcodec;avfilter;avutil;Protobuf_LIBRARY
> linked by target "dali_test.bin" in directory /home/x/dali/dali
> Protobuf_LIBRARY
> linked by target "dali" in directory /home/x/dali/dali
> linked by target "dali_benchmark.bin" in directory /home/x/dali/dali
> -- Configuring incomplete, errors occurred!
> See also "/home/x/dali/build/CMakeFiles/CMakeOutput.log".
> See also "/home/x/dali/build/CMakeFiles/CMakeError.log".
> error like this ......,Sincerely thank you !!!! ,but do you sure for that retrying again will be useful?
> clean build directory
> git pull
> build
> 
> I
> wil try right now
> 
> you will like it. you can star this repo.

hhhhhhhhhhhh
